process-engine/flow_node_instance.repository.sequelize

package.json
src/flow_node_instance_repository.ts
src/schemas/process_token.ts

Update `process_engine_contracts` package, so that no old packages will get installed anymore as inherited dependencies.
Install the package and see that packages like `core_contracts` or `foundation` will no longer be installed as dependencies.

Use feature branch for process engine contracts

---

package.json
src/flow_node_instance_repository.ts
src/schemas/flow_node_instance.ts

Depends on:
* https://github.com/process-engine/process_engine_contracts/pull/55
* added `error` property to `FlowNodeInstance` schema as an optional string
* implemented `persistOnError`-method
See https://github.com/process-engine/process_engine_meta/pull/118.

Add error persistance

---

PULL_REQUEST_TEMPLATE.md
package.json
src/flow_node_instance_repository.ts
src/model_loader.ts
src/schemas/flow_node_instance.ts
src/schemas/process_token.ts

Requires: https://github.com/process-engine/process_engine_contracts/pull/62
Part of the Heatmap feature. 
- Suspend and Resume are no longer treated as a flag, but as an actual FlowNodeState
- FlowNodeInstances will no longer have only a single process token that gets updated every time its state changes
- Instead, each state change will produce its own process token. This will enable the heatmap to display token values for each stage of the FlowNodeInstances lifecycle
- Add `flowNodeInstanceId` to the ProcessTokens schema
- Make the relations between ProcessToken and FlowNodeInstance explicit (i.e. both directions are now defined in the model loader)
- Reorder the query- and persist- methods so that they are grouped together and no longer scattered across the repository
- Also change …

♻️ Feature/store enter and exit token separately

---

package.json
src/flow_node_instance_repository.ts
src/schemas/flow_node_instance.ts

**Changes:**
1. Remove obsolete and unused `isSuspended` column from FlowNodeInstance Schema (Migration will be added to the runtime, when this version is implemented there)
2. Add `querySpecificFlowNode` function to the FlowNodeInstance persistence layer, which allows to retrieve a specific FlowNodeInstance by its correlationId, processModelId and flowNodeId (required for the heatmap)
3. Change return type of queryByFlowNodeId into an Array, since FlowNodeIds are not necessarily unique in this context
PR: #66
Run requests against this repository.
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge …

✨ Add query for specific flow node

---

package.json
src/flow_node_instance_repository.ts

**Changes:**
1. Add the following properties to the`FlowNodeInstance` object to allow for easier querying:
- `processInstanceId`
- `processModelId`
- `correlationId`
Note that this does not affect the database.
PR: #12
Make queries against the repository.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …

✨ Inspect correlation features

---

package.json
src/flow_node_instance_repository.ts

---
**Changes:**
1. Throw a 404 Error when a flow node id was not found while executing `queryByFlowNodeId()` or `querySpecificFlowNode()`
**Issues:**
PR: #PullRequest
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes …

🐛 Throw a 404 Error if a flow node to a given flow node id was not found

---

package.json
src/flow_node_instance_repository.ts

---
**Changes:**
1. Throw a 404 error instead of a 500 Error when a flow node instance with a given ID was not found for the requested Process Instance. 
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/103
PR: #14
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy …

🐛 :bug: Fix wrong error message when a FlowNode Instance was not found

---

package.json
src/flow_node_instance_repository.ts
src/schemas/flow_node_instance.ts

**Changes:**
1. Adjust parameters of persists methods.
2. Adds the new field "flowNodeType" to the schema.
**Issues:**
Relates to: https://github.com/process-engine/process_engine_runtime/issues/133
PR: #15
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example …

✨Add Type to FlowNode 

---

package.json
src/flow_node_instance_repository.ts

**Changes:**
The FlowNodeInstances type was not parsed in the converter methods.
This is now fixed.
PR: #16
Query FlowNodeInstances and notice that the type is now attached to them.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR
</code>
</pre> …

🐛 Add bpmn type to flownode converter

---

package.json
src/flow_node_instance_repository.ts
src/schemas/flow_node_instance.ts

**Changes:**
1. Adds the field `eventType` to the flow node instace.
**Issues:**
Relates to: https://github.com/process-engine/process_engine_runtime/issues/112
PR: #PullRequest
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …

✨Add Event Types

---

package.json
src/flow_node_instance_repository.ts

**Changes:**
1. Add delete process model functionality
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/64
PR: #19
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/141**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …

✨ Add Delete Process Model Functionality

---

package.json
src/flow_node_instance_repository.ts
src/schemas/flow_node_instance.ts

**Changes:**
1. Add `previousFlowNodeInstanceId` to the `persistOnEnter` logic for the `FlowNodeInstanceService`.
* This allows each FlowNodeInstance to get information about the FNI that was executed previously
**Issues:**
Prerequisite of #167
PR: #20
All should work as before, except that each FNI will now handle the `previousFlowNodeInstance` property.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre> …

✨ Add "previousFlowNodeInstanceId" to FlowNodeHandlers

---

package.json
src/flow_node_instance_repository.ts

**Changes:**
1. Add ordering to each query function (this was applied, because Sequelize doesn't guarantee a sorted dataset, unless ordering is explicitly stated).
2. Reorder the functions to put them into proper context.
3. Add more context-specific queries to reduce the number of database requests necessary for complex use cases.
PR: #22
Use the Repository to query FlowNodeInstances.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the …

✨ Add more UseCase specific queries

---

ioc_module.js
package.json
src/flow_node_instance_repository.ts
src/schemas/flow_node_instance.ts
src/schemas/process_token.ts

**Changes:**
1. Update dependency
2. Add SequelizeConnectionManager as Dependency to Container Registration
3. Add Constructor for SequelizeConnectionManager
4. Remove the definition of the primary key column `id` and let sequelize auto-generate that column instead.
This resolves an issue that we are currently experiencing, when trying to use UUIDs with primary key columns (i.e. it doesn't work).
5. Use `~` type dependencies to make it easier to apply bugfixes.
**Issues:**
Closes #https://github.com/process-engine/process_engine_runtime/issues/168
PR: #23 
---
<details>
<summary>
:warning: …

♻️Add SequelizeConnectionManager Through IoC

---

package.json
src/flow_node_instance_repository.ts

**Changes:**
1. Add Queries For Correlation And ProcessModel
PR: #26
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand …

✨ Add Queries For Correlation And ProcessModel

---

ioc_module.js
package.json
src/flow_node_instance_repository.ts

**Changes:**
1. Implement repository disposal, by use of the `disposableDiscoveryTag` and the `IDisposable` interface.
2. Add some logging during intiialization and disposal stages.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/146
PR: #27
This is best viewed during the integrationtests of any of the meta repositories or the runtime. When the repository gets disposed through the bootstrapper, you'll see the corresponding log output.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix …

✨⚡️ Implement disposal pattern

---

package.json
src/flow_node_instance_repository.ts
src/schemas/flow_node_instance.ts
src/schemas/process_token.ts

**Changes:**
Move the following columns from the `ProcessToken` table to the `FlowNodeInstance` table:
- `processInstanceId`
- `processModelId`
- `correlationId`
- `identity`
- `callerId` => was renamend to `parentProcessInstanceId`
**Issues:**
Closes: #18 
PR: #25
Since the return values are derived from the `ProcessEngineContracts`, all should work like before. These changes are purely internal to the database.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your …

♻️ Refactor DataModels

---

package.json
src/flow_node_instance_repository.ts

**Changes:**
Add the `identity` and `parentProcessInstanceId` properties to all returned `FlowNodeInstances`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/198
PR: #30
Make any query for FlowNodeInstances and see that they now contain the `identity` and `parentProcessInstanceId` properties.

✨ Get instances and tasks by identity

---

src/flow_node_instance_repository.ts

> Related to https://github.com/process-engine/process_engine_runtime/pull/194
**Changes:**
1. Add query for processInstanceId
PR: #29 
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: …

✨ Add Get Token by Process Instance Functionality

---

package.json
src/flow_node_instance_repository.ts

> Related to https://github.com/process-engine/process_engine_runtime/pull/207
**Changes:**
1. Add query for suspended by ProcessInstance
PR: #32
**- Have a look at process-engine/bpmn-studio#1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR …

✨ Add Query For Suspended By ProcessInstance

---

package.json
src/flow_node_instance_repository.ts
src/model_loader.ts
src/schemas/flow_node_instance.ts
src/schemas/process_token.ts

**Changes:**
1. Import all contracts from `@process-engine/flow_node_instance.contracts`.
2. Remove all references to `@process-engine/process_engine_contracts`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/84
PR: #33

♻️ Implement new persistence layer

---

package.json
src/flow_node_instance_repository.ts

**Changes:**
1. Add queryFlowNodesByProcessInstanceId Method
**Issues:**
Closes #https://github.com/process-engine/bpmn-studio/issues/1464
PR: #34 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration …

✨Add queryFlowNodesByProcessInstanceId

---

package.json
src/flow_node_instance_repository.ts

1. Add `offset` and `limit` to all queries that return a list
2. Update author- and maintainer info in package.json
Part of https://github.com/process-engine/process_engine_runtime/issues/379
PR: #4

✨ Add limit and offset to list queries
